GET https://gh649qzq1j.execute-api.us-east-1.amazonaws.com/prod/concepts
###

POST https://gh649qzq1j.execute-api.us-east-1.amazonaws.com/prod/concepts
content-type: application/json

// HTTP request message syntax requires a blank line (CRLF) between the headers and the message body
{
  "displayName": "Glaucoma"
}
###

PUT https://gh649qzq1j.execute-api.us-east-1.amazonaws.com/prod/concepts?id=ba7c041e-0b34-4a56-b296-e9d2bc802c30
content-type: application/json

{
  "name": "Glaucoma2"
}
###
